version: 1
disable_existing_loggers: False
handlers:
    console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: basic
        level: INFO
    console_extended:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: extended
    console_file:
        class: logging.FileHandler
        filename: 'output.log'
        formatter: extended
        level: DEBUG
    audit_file:
        class: logging.FileHandler
        filename: 'audit.log'
        formatter: extended
        level: DEBUG


formatters:
    basic:
        style: "{"
        format: "{levelname:8s} {name:15s} {message}"
    extended:
        style: "{"
        format: "{asctime:s} {levelname:10s} {name:15s} {message}"
        datefmt: '%Y-%m-%d %H:%M:%S'

loggers:
    verbose:
        handlers: [console]
        level: INFO
        propagate: True
    audit:
        handlers: [audit_file]
        level: INFO
        propagate: True
root:
    handlers: [console, console_file]
    level: NOTSET