version: '3.5'
services:
  dimensigon:
    image: dimensigon/dimensigon
    build: .
    volumes:
      - ./dimensigon:/python_project/dimensigon
      - ./tests:/python_project/tests
    stdin_open: true
    tty: true
