"""initial

Revision ID: 4a4052e40afb
Revises: 
Create Date: 2020-04-27 19:43:40.524877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4052e40afb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    data_upgrades()

def downgrade():
    data_downgrades()
    schema_downgrades()

def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('D_action_template',
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('ANSIBLE', 'PYTHON', 'NATIVE', 'ORCHESTRATION', name='actiontype'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('expected_stdout', sa.Text(), nullable=True),
    sa.Column('expected_stderr', sa.Text(), nullable=True),
    sa.Column('expected_rc', sa.Integer(), nullable=True),
    sa.Column('system_kwargs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_D_action_template')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_D_action_template_name'))
    )
    op.create_table('D_orchestration',
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stop_on_error', sa.Boolean(), nullable=True),
    sa.Column('stop_undo_on_error', sa.Boolean(), nullable=True),
    sa.Column('undo_on_error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_D_orchestration')),
    sa.UniqueConstraint('name', 'version', name='D_orchestration_uq01')
    )
    op.create_table('D_server',
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('granules', sa.UnicodeText(), nullable=True),
    sa.Column('me', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_D_server')),
    sa.UniqueConstraint('name', name=op.f('uq_D_server_name'))
    )
    op.create_table('D_service',
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('last_ping', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_D_service'))
    )
    op.create_table('D_software',
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_D_software')),
    sa.UniqueConstraint('name', 'version', name='D_software_u01')
    )
    op.create_table('D_user',
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('user', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('groups', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_D_user')),
    sa.UniqueConstraint('user', name='D_user_uq01')
    )
    op.create_table('L_catalog',
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('entity', name=op.f('pk_L_catalog')),
    sa.UniqueConstraint('entity', name=op.f('uq_L_catalog_entity'))
    )
    op.create_table('L_dimension',
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('private', sa.BLOB(), nullable=True),
    sa.Column('public', sa.BLOB(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_L_dimension')),
    sa.UniqueConstraint('name', name=op.f('uq_L_dimension_name')),
    sa.UniqueConstraint('private', name=op.f('uq_L_dimension_private')),
    sa.UniqueConstraint('public', name=op.f('uq_L_dimension_public'))
    )
    op.create_table('L_locker',
    sa.Column('scope', sa.Enum('ORCHESTRATION', 'CATALOG', 'UPGRADE', name='scope'), nullable=False),
    sa.Column('state', sa.Enum('UNLOCKED', 'PREVENTING', 'LOCKED', name='state'), nullable=False),
    sa.Column('applicant', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('scope', name=op.f('pk_L_locker'))
    )
    op.create_table('D_gate',
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('server_id', sa.CHAR(), nullable=True),
    sa.Column('dns', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.CHAR(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['D_server.id'], name=op.f('fk_D_gate_server_id_D_server')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_D_gate')),
    sa.UniqueConstraint('server_id', 'ip', 'dns', name=op.f('uq_D_gate_server_id'))
    )
    op.create_table('D_log',
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('src_server_id', sa.CHAR(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('include', sa.Text(), nullable=True),
    sa.Column('exclude', sa.Text(), nullable=True),
    sa.Column('dst_server_id', sa.CHAR(), nullable=False),
    sa.Column('dest_folder', sa.Text(), nullable=True),
    sa.Column('recursive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dst_server_id'], ['D_server.id'], name=op.f('fk_D_log_dst_server_id_D_server')),
    sa.ForeignKeyConstraint(['src_server_id'], ['D_server.id'], name=op.f('fk_D_log_src_server_id_D_server')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_D_log')),
    sa.UniqueConstraint('src_server_id', 'target', 'dst_server_id', name=op.f('uq_D_log_src_server_id'))
    )
    op.create_table('D_service_orchestration',
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('service_id', sa.CHAR(), nullable=True),
    sa.Column('orchestration_id', sa.CHAR(), nullable=True),
    sa.Column('execution_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orchestration_id'], ['D_orchestration.id'], name=op.f('fk_D_service_orchestration_orchestration_id_D_orchestration')),
    sa.ForeignKeyConstraint(['service_id'], ['D_service.id'], name=op.f('fk_D_service_orchestration_service_id_D_service')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_D_service_orchestration'))
    )
    op.create_table('D_software_server',
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('software_id', sa.CHAR(), nullable=False),
    sa.Column('server_id', sa.CHAR(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['D_server.id'], name=op.f('fk_D_software_server_server_id_D_server')),
    sa.ForeignKeyConstraint(['software_id'], ['D_software.id'], name=op.f('fk_D_software_server_software_id_D_software')),
    sa.PrimaryKeyConstraint('software_id', 'server_id', name=op.f('pk_D_software_server'))
    )
    op.create_table('D_step',
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('orchestration_id', sa.CHAR(), nullable=False),
    sa.Column('action_template_id', sa.CHAR(), nullable=False),
    sa.Column('undo', sa.Boolean(), nullable=False),
    sa.Column('stop_on_error', sa.Boolean(), nullable=True),
    sa.Column('stop_undo_on_error', sa.Boolean(), nullable=True),
    sa.Column('undo_on_error', sa.Boolean(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('expected_stdout', sa.Text(), nullable=True),
    sa.Column('expected_stderr', sa.Text(), nullable=True),
    sa.Column('expected_rc', sa.Integer(), nullable=True),
    sa.Column('system_kwargs', sa.JSON(), nullable=True),
    sa.Column('target', sa.UnicodeText(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_template_id'], ['D_action_template.id'], name=op.f('fk_D_step_action_template_id_D_action_template')),
    sa.ForeignKeyConstraint(['orchestration_id'], ['D_orchestration.id'], name=op.f('fk_D_step_orchestration_id_D_orchestration')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_D_step'))
    )
    op.create_table('L_transfer',
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('software_id', sa.CHAR(), nullable=False),
    sa.Column('dest_path', sa.Text(), nullable=False),
    sa.Column('num_chunks', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING_CHUNKS', 'IN_PROGRESS', 'COMPLETED', 'CHECKSUM_ERROR', 'SIZE_ERROR', 'CANCELED', name='status'), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('started_on', sa.DateTime(), nullable=True),
    sa.Column('ended_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['D_software.id'], name=op.f('fk_L_transfer_software_id_D_software')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_L_transfer'))
    )
    op.create_table('D_step_step',
    sa.Column('parent_step_id', sa.CHAR(), nullable=False),
    sa.Column('step_id', sa.CHAR(), nullable=False),
    sa.ForeignKeyConstraint(['parent_step_id'], ['D_step.id'], name=op.f('fk_D_step_step_parent_step_id_D_step')),
    sa.ForeignKeyConstraint(['step_id'], ['D_step.id'], name=op.f('fk_D_step_step_step_id_D_step')),
    sa.PrimaryKeyConstraint('parent_step_id', 'step_id', name=op.f('pk_D_step_step'))
    )
    op.create_table('L_execution',
    sa.Column('id', sa.CHAR(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('rc', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('executor_id', sa.CHAR(), nullable=True),
    sa.Column('step_id', sa.CHAR(), nullable=True),
    sa.Column('execution_server_id', sa.CHAR(), nullable=True),
    sa.Column('source_server_id', sa.CHAR(), nullable=True),
    sa.Column('service_id', sa.CHAR(), nullable=True),
    sa.ForeignKeyConstraint(['execution_server_id'], ['D_server.id'], name=op.f('fk_L_execution_execution_server_id_D_server')),
    sa.ForeignKeyConstraint(['executor_id'], ['D_user.id'], name=op.f('fk_L_execution_executor_id_D_user')),
    sa.ForeignKeyConstraint(['service_id'], ['D_service.id'], name=op.f('fk_L_execution_service_id_D_service')),
    sa.ForeignKeyConstraint(['source_server_id'], ['D_server.id'], name=op.f('fk_L_execution_source_server_id_D_server')),
    sa.ForeignKeyConstraint(['step_id'], ['D_step.id'], name=op.f('fk_L_execution_step_id_D_step')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_L_execution'))
    )
    op.create_table('L_route',
    sa.Column('destination_id', sa.CHAR(), nullable=False),
    sa.Column('proxy_server_id', sa.CHAR(), nullable=True),
    sa.Column('gate_id', sa.CHAR(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['D_server.id'], name=op.f('fk_L_route_destination_id_D_server')),
    sa.ForeignKeyConstraint(['gate_id'], ['D_gate.id'], name=op.f('fk_L_route_gate_id_D_gate')),
    sa.ForeignKeyConstraint(['proxy_server_id'], ['D_server.id'], name=op.f('fk_L_route_proxy_server_id_D_server')),
    sa.PrimaryKeyConstraint('destination_id', name=op.f('pk_L_route'))
    )
    # ### end Alembic commands ###

def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('L_route')
    op.drop_table('L_execution')
    op.drop_table('D_step_step')
    op.drop_table('L_transfer')
    op.drop_table('D_step')
    op.drop_table('D_software_server')
    op.drop_table('D_service_orchestration')
    op.drop_table('D_log')
    op.drop_table('D_gate')
    op.drop_table('L_locker')
    op.drop_table('L_dimension')
    op.drop_table('L_catalog')
    op.drop_table('D_user')
    op.drop_table('D_software')
    op.drop_table('D_service')
    op.drop_table('D_server')
    op.drop_table('D_orchestration')
    op.drop_table('D_action_template')
    # ### end Alembic commands ###

def data_upgrades():
    import uuid
    """Add any optional data upgrade migrations here!"""
    lock_table = sa.table('L_locker',
                          sa.column('scope', sa.String),
                          sa.column('state', sa.String),
                          sa.column('priority', sa.Integer),
                          )

    op.bulk_insert(lock_table,
                   [{'scope': 'UPGRADE', 'state': 'UNLOCKED'},
                    {'scope': 'ORCHESTRATION', 'state': 'UNLOCKED'},
                    {'scope': 'CATALOG', 'state': 'UNLOCKED'}
                    ]
                   )


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    op.execute("delete from L_locker")